name: Master

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *' # kjorer hver 5. minutt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # checkout the repository content to github runner
      - name: Running
        run: |
          echo "Running!"